# Spring AI 的配置
spring:
  # Spring AI 配置
  ai:
    # Spring AI MCP 配置
    mcp:
      # Spring AI Client 配置
      client:
        # 是否启用 Spring AI Client
        enabled: true
        # Client 名称
        name: spring-ai-mcp-client
        # Client 版本
        version: 1.0.0
        # Client 类型
        type: sync
        # Client 初始化超时时间或重试配置
        request-timeout: 120s
        # 工具回调配置
        toolcallback:
          # 是否启用工具回调
          enabled: true
        # 使用 streamable-http 方式, 添加如下配置
        streamable-http:
          # 使用 streamable-http 方式, 配置 MCP Server 连接
          connections:
            # 使用 streamable-http 方式, 配置 MCP Server
            python-mcp-web-serach-server:
              # 使用 streamable-http 方式, 配置 MCP Server 的 url
              url: http://127.0.0.1:8084
              endpoint: /mcp
            # Java 的 MCP Server 配置
            java-file-mcp-server:
              # Java 的 MCP Server 的 url
              url: http://127.0.0.1:8085
              endpoint: /mcp


# 自定义的 MCP 服务配置 - 暂为使用
mcp:
  # 自定义的 MCP 服务端配置 - 暂未使用
  server:
    # 自定义的 MCP 服务端 URL 配置, List 集合, 因为可能存在多个 MCP Server - 暂未使用
    urls:
      - "http://127.0.0.1:8084/sse"