# Spring AI 的配置
spring:
  # Spring AI 配置
  ai:
    # Spring AI MCP 配置
    mcp:
      # Spring AI Client 配置
      client:
        # 是否启用 Spring AI Client
        enabled: true
        # Client 名称
        name: spring-ai-mcp-client
        # Client 版本
        version: 1.0.0
        # Client 类型
        type: sync
        # Client 初始化超时时间或重试配置
        request-timeout: 120s
        # 工具回调配置
        toolcallback:
          # 是否启用工具回调
          enabled: true
        # 使用 streamable-http 方式, 添加如下配置
        streamable-http:
          # 使用 streamable-http 方式, 配置 MCP Server 连接
          connections:
            # 使用 streamable-http 方式, 配置 MCP Server
            python-mcp-web-serach-server:
              # 使用 streamable-http 方式, 配置 MCP Server 的 url
              url: http://127.0.0.1:8084
              endpoint: /mcp
            # Java 的 MCP Server 配置
            java-file-mcp-server:
              # Java 的 MCP Server 的 url
              url: http://127.0.0.1:8085
              endpoint: /mcp


# 自定义的 MCP 服务配置
mcp:
  # 自定义的 MCP 服务描述信息列表,用于后续的自动添加系统提示词
  descriptions:
    - 数据获取工具(fetch_data), 从网页/文件/API中获取结构化数据
    - 数据分析工具(analyze_data), 对已获取的数据进行统计分析（需要先使用fetch_data获取数据）
    - 访问指定URL并提取网页内容工具(fetch_webpage), 访问 URL 并提取网页内容
    - 为前端可视化生成图表数据（JSON格式）工具(generate_chart_data), 根据分析结果生成图表数据（JSON格式）
    - 根据已获取的数据和分析结果生成结构化报告工具(generate_report), 生成包含数据和分析结果的结构化报告
    - 对时间序列数据进行趋势分析工具(trend_analysis), 分析时间序列数据的趋势
    - 通过网络搜索引擎搜索最新的信息工具(web_search), 从网络中搜索实时信息
    - 如果需要对一定内容进行保存到本机电脑时, 请调用文件操作MCP工具 FileOperateMcpTool
